name: Sync from Upstream using PAT

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this fork
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/ThatCoders/thatcoders.github.io.git
          git fetch upstream

      - name: Merge upstream/master into fork/master
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories -m "Auto-sync from upstream/master"

      - name: Push changes using PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.G_TK }}@github.com/${{ github.repository }}.git
          git push origin master
