name: Sync from Upstream

on:
  schedule:
    - cron: '0 6,12,18,2 * * *'  # 每天 6/12/18/2 点 UTC 自动同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone forked repo with G_TK
        run: |
          git clone https://x-access-token:${{ secrets.G_TK }}@github.com/${{ github.repository }}.git repo
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and reset to upstream/master
        run: |
          cd repo
          git remote add upstream https://github.com/ThatCoders/thatcoders.github.io.git
          git fetch upstream
          git checkout -B master upstream/master

      - name: Force push master to origin using G_TK
        run: |
          cd repo
          git push -f https://x-access-token:${{ secrets.G_TK }}@github.com/${{ github.repository }}.git master

      - name: Trigger Vercel Deploy Hook
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_VvQVpEZ8EmNAx5wmyraBZloThrzx/ChMfH5aEg7"
