name: Sync from Upstream using G_TK

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 凌晨2点
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with G_TK
        run: |
          git clone https://x-access-token:${{ secrets.G_TK }}@github.com/${{ github.repository }}.git repo
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream and fetch
        run: |
          cd repo
          git remote add upstream https://github.com/ThatCoders/thatcoders.github.io.git
          git fetch upstream

      - name: Merge upstream/master into fork/master
        run: |
          cd repo
          git checkout master
          git merge upstream/master --allow-unrelated-histories -m "Auto-sync from upstream/master"

      - name: Push changes using G_TK
        run: |
          cd repo
          git push https://x-access-token:${{ secrets.G_TK }}@github.com/${{ github.repository }}.git master
